
// This file has been generated by the GUI designer. Do not modify.
namespace TextureMerger
{
	public partial class FileSelector
	{
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label textField;
		private global::Gtk.FileChooserButton fileBrowser;
		private global::Gtk.Image previewImage;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TextureMerger.FileSelector
			global::Stetic.BinContainer.Attach (this);
			this.Name = "TextureMerger.FileSelector";
			// Container child TextureMerger.FileSelector.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.textField = new global::Gtk.Label ();
			this.textField.Name = "textField";
			this.textField.LabelProp = global::Mono.Unix.Catalog.GetString ("text");
			this.hbox2.Add (this.textField);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.textField]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(7));
			// Container child hbox2.Gtk.Box+BoxChild
			this.fileBrowser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
			this.fileBrowser.Name = "fileBrowser";
			this.hbox2.Add (this.fileBrowser);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fileBrowser]));
			w2.Position = 1;
			w2.Padding = ((uint)(2));
			// Container child hbox2.Gtk.Box+BoxChild
			this.previewImage = new global::Gtk.Image ();
			this.previewImage.Name = "previewImage";
			this.hbox2.Add (this.previewImage);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.previewImage]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(5));
			this.Add (this.hbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.fileBrowser.SelectionChanged += new global::System.EventHandler (this.OnFileBrowserSelectionChanged);
		}
	}
}
