
// This file has been generated by the GUI designer. Do not modify.
namespace TextureMerger
{
	public partial class ImageSelectorRow
	{
		private global::Gtk.HBox rowControl;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label lblEmpty1;
		
		private global::Gtk.Button rowMinus;
		
		private global::Gtk.Label lblEmpty3;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Label lblEmpty2;
		
		private global::Gtk.Button rowPlus;
		
		private global::Gtk.Label lblEmpty4;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TextureMerger.ImageSelectorRow
			global::Stetic.BinContainer.Attach (this);
			this.Name = "TextureMerger.ImageSelectorRow";
			// Container child TextureMerger.ImageSelectorRow.Gtk.Container+ContainerChild
			this.rowControl = new global::Gtk.HBox ();
			this.rowControl.Name = "rowControl";
			this.rowControl.Spacing = 6;
			// Container child rowControl.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblEmpty1 = new global::Gtk.Label ();
			this.lblEmpty1.Name = "lblEmpty1";
			this.vbox2.Add (this.lblEmpty1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblEmpty1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.rowMinus = new global::Gtk.Button ();
			this.rowMinus.WidthRequest = 22;
			this.rowMinus.CanFocus = true;
			this.rowMinus.Name = "rowMinus";
			this.rowMinus.UseUnderline = true;
			this.rowMinus.Label = global::Mono.Unix.Catalog.GetString ("-");
			this.vbox2.Add (this.rowMinus);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.rowMinus]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblEmpty3 = new global::Gtk.Label ();
			this.lblEmpty3.Name = "lblEmpty3";
			this.vbox2.Add (this.lblEmpty3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblEmpty3]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.rowControl.Add (this.vbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.rowControl [this.vbox2]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child rowControl.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblEmpty2 = new global::Gtk.Label ();
			this.lblEmpty2.Name = "lblEmpty2";
			this.vbox3.Add (this.lblEmpty2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblEmpty2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.rowPlus = new global::Gtk.Button ();
			this.rowPlus.WidthRequest = 22;
			this.rowPlus.CanFocus = true;
			this.rowPlus.Name = "rowPlus";
			this.rowPlus.UseUnderline = true;
			this.rowPlus.Label = global::Mono.Unix.Catalog.GetString ("+");
			this.vbox3.Add (this.rowPlus);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.rowPlus]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblEmpty4 = new global::Gtk.Label ();
			this.lblEmpty4.Name = "lblEmpty4";
			this.vbox3.Add (this.lblEmpty4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblEmpty4]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.rowControl.Add (this.vbox3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.rowControl [this.vbox3]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.rowControl);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.rowMinus.Clicked += new global::System.EventHandler (this.OnRowMinusClicked);
			this.rowPlus.Clicked += new global::System.EventHandler (this.OnRowPlusClicked);
		}
	}
}
