
// This file has been generated by the GUI designer. Do not modify.
namespace TextureMerger
{
	public partial class MainWindows
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action PreferencesAction;
		private global::Gtk.Action ClearAction;
		private global::Gtk.Action QuitAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar menubar1;
		private global::Gtk.Label title;
		private global::Gtk.HSeparator hseparator3;
		private global::TextureMerger.FileSelector selector1;
		private global::TextureMerger.FileSelector selector2;
		private global::TextureMerger.FileSelector selector3;
		private global::TextureMerger.FileSelector selector4;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label labelOutput;
		private global::Gtk.Label lblPath;
		private global::Gtk.Entry txtFilename;
		private global::Gtk.Label lblExtension;
		private global::Gtk.Button BtnBrowse;
		private global::Gtk.Button btnGo;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TextureMerger.MainWindows
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.PreferencesAction = new global::Gtk.Action ("PreferencesAction", global::Mono.Unix.Catalog.GetString ("Preferences"), null, null);
			this.PreferencesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Preferences");
			w1.Add (this.PreferencesAction, null);
			this.ClearAction = new global::Gtk.Action ("ClearAction", global::Mono.Unix.Catalog.GetString ("Clear"), null, null);
			this.ClearAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Clear");
			w1.Add (this.ClearAction, null);
			this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, null);
			this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
			w1.Add (this.QuitAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "TextureMerger.MainWindows";
			this.Title = global::Mono.Unix.Catalog.GetString ("Texture Merger");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(3));
			this.DefaultWidth = 500;
			this.DefaultHeight = 400;
			// Container child TextureMerger.MainWindows.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='PreferencesAction' action='PreferencesAction'/><separator/><menuitem name='ClearAction' action='ClearAction'/><menuitem name='QuitAction' action='QuitAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.title = new global::Gtk.Label ();
			this.title.Name = "title";
			this.title.LabelProp = global::Mono.Unix.Catalog.GetString ("Texture Merger");
			this.title.Justify = ((global::Gtk.Justification)(2));
			this.vbox1.Add (this.title);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.title]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vbox1.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator3]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.selector1 = new global::TextureMerger.FileSelector ();
			this.selector1.Events = ((global::Gdk.EventMask)(256));
			this.selector1.Name = "selector1";
			this.vbox1.Add (this.selector1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.selector1]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.selector2 = new global::TextureMerger.FileSelector ();
			this.selector2.Events = ((global::Gdk.EventMask)(256));
			this.selector2.Name = "selector2";
			this.vbox1.Add (this.selector2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.selector2]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.selector3 = new global::TextureMerger.FileSelector ();
			this.selector3.Events = ((global::Gdk.EventMask)(256));
			this.selector3.Name = "selector3";
			this.vbox1.Add (this.selector3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.selector3]));
			w7.Position = 5;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.selector4 = new global::TextureMerger.FileSelector ();
			this.selector4.Events = ((global::Gdk.EventMask)(256));
			this.selector4.Name = "selector4";
			this.vbox1.Add (this.selector4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.selector4]));
			w8.Position = 6;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox1.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator2]));
			w9.Position = 7;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.labelOutput = new global::Gtk.Label ();
			this.labelOutput.Name = "labelOutput";
			this.labelOutput.LabelProp = global::Mono.Unix.Catalog.GetString ("Output: ");
			this.hbox6.Add (this.labelOutput);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.labelOutput]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			w10.Padding = ((uint)(5));
			// Container child hbox6.Gtk.Box+BoxChild
			this.lblPath = new global::Gtk.Label ();
			this.lblPath.Name = "lblPath";
			this.lblPath.LabelProp = global::Mono.Unix.Catalog.GetString ("~/TextureMerger/");
			this.hbox6.Add (this.lblPath);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lblPath]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.txtFilename = new global::Gtk.Entry ();
			this.txtFilename.CanFocus = true;
			this.txtFilename.Name = "txtFilename";
			this.txtFilename.Text = global::Mono.Unix.Catalog.GetString ("output");
			this.txtFilename.IsEditable = true;
			this.txtFilename.InvisibleChar = '•';
			this.hbox6.Add (this.txtFilename);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.txtFilename]));
			w12.Position = 2;
			// Container child hbox6.Gtk.Box+BoxChild
			this.lblExtension = new global::Gtk.Label ();
			this.lblExtension.Name = "lblExtension";
			this.lblExtension.LabelProp = global::Mono.Unix.Catalog.GetString (".png");
			this.hbox6.Add (this.lblExtension);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lblExtension]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.BtnBrowse = new global::Gtk.Button ();
			this.BtnBrowse.CanFocus = true;
			this.BtnBrowse.Name = "BtnBrowse";
			this.BtnBrowse.UseUnderline = true;
			this.BtnBrowse.Label = global::Mono.Unix.Catalog.GetString ("...");
			this.hbox6.Add (this.BtnBrowse);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.BtnBrowse]));
			w14.Position = 4;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.btnGo = new global::Gtk.Button ();
			this.btnGo.CanFocus = true;
			this.btnGo.Name = "btnGo";
			this.btnGo.UseUnderline = true;
			this.btnGo.Label = global::Mono.Unix.Catalog.GetString ("Merge");
			this.hbox6.Add (this.btnGo);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.btnGo]));
			w15.Position = 5;
			w15.Expand = false;
			w15.Fill = false;
			w15.Padding = ((uint)(5));
			this.vbox1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
			w16.Position = 8;
			w16.Expand = false;
			w16.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.PreferencesAction.Activated += new global::System.EventHandler (this.OnPreferencesActionActivated);
			this.ClearAction.Activated += new global::System.EventHandler (this.OnClearActionActivated);
			this.QuitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
			this.BtnBrowse.Clicked += new global::System.EventHandler (this.OnBtnBrowseClicked);
			this.btnGo.Clicked += new global::System.EventHandler (this.OnBtnGoClicked);
		}
	}
}
